### ISSUE TITLE
Encode user input to avoid XSS

### ISSUE THREAD

**Issue by robertaboukhalil** [quinlan-lab/bedqc#13]
Hey folks, awesome tool!

It seems the app executes any javascript that might be found inside a BED file. For example, using the following BED file launches an alert box:

```html
chr2<script>alert('hello!')</script>	789	1020
```

I don't *think* it's a security issue since the data is local/there's no auth in your app, so feel free to close, but just FYI :)

**Comment by brwnj** [comment]
thanks for pointing this out.
