### ISSUE TITLE
Overlap counts not working

### ISSUE THREAD

**Issue by arq5x** [quinlan-lab/bedqc#6]
When intersecting refseq in GRCh37 with the Ensembl whole gene track, here is what I get (1 hit on chr1)
![image](https://user-images.githubusercontent.com/72291/148693608-bd1c658b-6380-4236-b0d4-eabdb4544e02.png)

**Comment by brwnj** [comment]
could you send this file to me? i tried a few versions and they all seem to work. might be something with chr names.

**Comment by brwnj** [comment]
fixed in e25e0ae57f40bd6dc82541cc63a43f024e8c68bf and https://github.com/quinlan-lab/bedqc/commit/1403cdf8840ef5f91ecdcc7f913a554409d43811.
